### ISSUE TITLE
no devicediscover when screen is off at background service mode

### ISSUE THREAD

**Issue by yeohcl99** [xabre/xamarin-bluetooth-le#570] opened 2022-03-14 08:37 UTC
adapter.DeviceDiscovered += (s, a) =>{} works well when the screen is on. But when screen is off on Android 9 the adapter.DeviceDiscovered += (s, a) =>{} no longer able to discover any near by BLE in background service mode. However when the screen comes on immediately able to scan the surrounding ble. Any idea how to resolve this issue?

## Steps to reproduce

1.  start adapter.devicediscovered running when screen on

2. turn screen off but start adapter.devicediscovered still running in background

3.detect no surrouding ble devices

## Expected behavior
adapter.devicedscovered should be able to scan surrounding ble devices in background servicemode be it screen on or off

## Actual behavior
adapter devicediscovered no surrounding device when screen is off

### Crashlog

NA

## Configuration

**Version of the Plugin:** 2.2 pre 2"

**Platform:** Android 9.1 pie 

**Device:** e.g. Samsung Galazy A32, Honor Play ...

**Comment by smsissuechecker** [comment] 2022-03-14 08:37
Hi @yeohcl99,

I'm the friendly issue checker.
Thanks for using the issue template :star2:
I appreciate it very much. I'm sure, the maintainers of this repository will answer, soon.

**Comment by janusw** [comment] 2022-03-14 20:01
> adapter.DeviceDiscovered += (s, a) =>{} works well when the screen is on. But when screen is off on Android 9 the adapter.DeviceDiscovered += (s, a) =>{} no longer able to discover any near by BLE in background service mode. However when the screen comes on immediately able to scan the surrounding ble.

Duplicate of #565!

> Any idea how to resolve this issue?

With a ScanFilter, it should be possible to scan when the screen is off.

**Closed by janusw** 2022-03-14 20:01 UTC

**Comment by yeohcl99** [comment] 2022-03-15 04:22
i do not get what you meant by Scanfilter. Below is my code and when screen is off it will never able to detect the Rssi in my background service.

                    ble = CrossBluetoothLE.Current;//added ble
                    adapter = CrossBluetoothLE.Current.Adapter;//added ble
           
                    var state = ble.State;
                    var status = Permissions.RequestAsync<Permissions.LocationWhenInUse>();
                    adapter.ScanTimeout = 30000;
                    

            while (true)
            {
                try
                {
                    adapter.DeviceDiscovered += (s, a) =>
                    {
                        if (Int16.Parse(a.Device.Rssi.ToString()) > -140)
                        {
                            try
                            {
                                    // do something
                            }
                            catch (Exception ex) { }

                        }
                    };
                    if (!ble.Adapter.IsScanning)//default ble 
                    {
                        adapter.ScanMode = ScanMode.LowLatency;
                        await adapter.StartScanningForDevicesAsync();

                    }
                    Thread.Sleep(5000);


                }
                catch (Exception ex)
                {

                }


            }

**Comment by janusw** [comment] 2022-03-15 08:03
> i do not get what you meant by Scanfilter.

https://developer.android.com/reference/android/bluetooth/le/ScanFilter

Note that scan filtering is currently not supported in xamarin-bluetooth-le, see #515.

> Below is my code and when screen is off it will never able to detect the Rssi in my background service.

Yes, that is expected behavior (as described in #565).

**Comment by janusw** [comment] 2022-05-01 09:22
Note: Scan filtering on Android was extended with #578 and #588. This expands your options for achieving device discovery when the screen is off.
